name: Gremlins

on:
    push:
    

jobs:
  gremlins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run Gremlins
        uses: go-gremlins/gremlins-action@v1
        with:
          version: latest
          args: --output=output.json
          workdir: controllers
      -  id: gremlins_run
         run: |
          mkdir -p test/dir
          go run gremlins --tags="tag1,tag2" > test/dir/gremlins-output.log
      - name: Capture Gremlins output
        if: success()
        run: |
          # Extraindo os valores desejados do output do Gremlins
          OUTPUT=$(cat test/dir/gremlins-output.log)
          KILLED=$(echo "$OUTPUT" | grep "Killed" | awk '{print $2}')
          LIVED=$(echo "$OUTPUT" | grep "Lived" | awk '{print $2}')
          NOT_COVERED=$(echo "$OUTPUT" | grep "Not covered" | awk '{print $3}')
          TEST_EFFICACY=$(echo "$OUTPUT" | grep "Test efficacy" | awk '{print $3}')
          MUTATOR_COVERAGE=$(echo "$OUTPUT" | grep "Mutator coverage" | awk '{print $3}')
          echo "Killed: $KILLED" > test/dir/gremlins-summary.txt
          echo "Lived: $LIVED" >> test/dir/gremlins-summary.txt
          echo "Not covered: $NOT_COVERED" >> test/dir/gremlins-summary.txt
          echo "Test efficacy: $TEST_EFFICACY" >> test/dir/gremlins-summary.txt
          echo "Mutator coverage: $MUTATOR_COVERAGE" >> test/dir/gremlins-summary.txt
          echo "$OUTPUT" > test/dir/gremlins-full-output.txt
      - name: Upload Gremlins summary
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: gremlins-summary
          path: test/dir/gremlins-summary.txt
      - name: Upload Gremlins full output
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: gremlins-full-output
          path: test/dir/gremlins-full-output.txt