name: Gremlins

on:
    push:
    

jobs:
  gremlins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Run Gremlins
        uses: go-gremlins/gremlins-action@v1
        with:
          version: latest
          workdir: controllers
      -  id: gremlins_run
         run: |
          mkdir -p test/dir
          
      - name: Upload Gremlins summary
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gremlins-summary
          path: /output.json
      
       